################################# Default configuration ###################
baseURL = ""
title = "RIT Linux Wiki"
theme = "dot"
enableEmoji = true
enableGitInfo = true

[markup.goldmark.renderer]
unsafe = true


################################# Navigation ################################
[[menu.main]]
weight = 10
name = "FAQ"
url = "faq"

[[menu.main]]
weight = 20
name = "pages"
url = "pages"
hasChildren = true

    [[menu.main]]
    parent = "pages"
    name = "Majors"
    url = "majors"
    weight = 10

    [[menu.main]]
    parent = "pages"
    name = "Networking"
    url = "network"
    weight = 10


############################# Default parameters ##########################
[params]
# Need to replace with SVG logo
#logo = "favicon.ico"

# customize color
primary_color = "#00BDF2"
body_color = "#e0e4e8"
text_color = "#636363"
text_color_dark = "#003E5D"
white_color = "#ffffff"
light_color = "#f8f9fa"

# font family (choose from https://fonts.google.com/)
font_family = "Open+Sans"

# contact form action (works with https://formspree.io)
contact_form_action = "#"


############################## Social links ##############################
# themify icon pack : https://themify.me/themify-icons

[[params.social]]
icon = "ti-github"
link = "https://github.com/RITlug/rit-linux-wiki"



################################ English Language ######################
[Languages.en]
languageName = "En"
languageCode = "en-us"
weight = 1
home = "Home"
copyright = "Creative Commons BY-SA 4.0"

# banner
[Languages.en.params.banner]
title = "RIT Linux Wiki"
subtitle = "A Wiki to help RIT students access university Resources using Linux."
bg_image = "img/banner.jpg"
placeholder = "Have a question? Search the site here."
